site_name: 我的个人网站
site_description: 基于mkdocs+GitHub Pages的个人站点
theme:
  name: material
nav:
  - 首页: index.md
  - 关于我: about.md  
  - 技术笔记:
      - 1:
          - 1.1 认知大前端之认知前端和互联网行业，从宏观到微观全面熟悉前端岗位: 1.1 认知大前端之认知前端和互联网行业，从宏观到微观全面熟悉前端岗位.md
          - 1.2 前端学习路线之认知前端岗位和互联网岗位: 1.2 前端学习路线之认知前端岗位和互联网岗位.md
          - 1.3 前端学习指南之前端学习方法论与前端学习指南: 1.3 前端学习指南之前端学习方法论与前端学习指南.md
      - 2:
          - 2.1 前端入门之前，必须搞懂互联网基础原理: 2.1 前端入门之前，必须搞懂互联网基础原理.md
          - 2.2 前端入门之什么是html，htmll的标签和书写规则: 2.2 前端入门之什么是html，htmll的标签和书写规则.md
      - 3:
          - 3.1 前端入门之html标签和属性之标题和段落标签、div标签以及html5特性详解: 3.1 前端入门之html标签和属性之标题和段落标签、div标签以及html5特性详解.md
          - 3.2 前端入门之html标签和属性之认识html5框架: 3.2 前端入门之html标签和属性之认识html5框架.md
      - 4:
          - 4.1 前端入门html标签属性之列表标签详解: 4.1 前端入门html标签属性之列表标签详解.md
          - 4.2 前端入门html标签之多媒体标签详解: 4.2 前端入门html标签之多媒体标签详解.md
      - 5:
          - 5.1 前端入门html标签属性之音视频标签属性讲解: 5.1 前端入门html标签属性之音视频标签属性讲解.md
          - 5.2 前端入门全集之html5区块化标签: 5.2 前端入门全集之html5区块化标签.md
      - 6:
          - 6.1 HTML标签属性之表单标签详解: 6.1 HTML标签属性之表单标签详解.md
          - 6.2 前端入门之HTML5新增表单控件: 6.2 前端入门之HTML5新增表单控件.md
          - 6.3 HTML综合应用以及复习汇总: 6.3 HTML综合应用以及复习汇总.md
      - 7:
          - 7.1 前端笔记神器Markdown文档上手指南和语法讲解: 7.1 前端笔记神器Markdown文档上手指南和语法讲解.md
          - 7.2 Markdown文档语法详解: 7.2 Markdown文档语法详解.md
          - 7.3 Markdown高阶语法应用: 7.3 Markdown高阶语法应用.md
          - 7.4 Markdown文档，个性化设置typora: 7.4 Markdown文档，个性化设置typora.md
      - 8:
          - 8.1 最全的前端Git使用教程之git入门: 8.1 最全的前端Git使用教程之git入门.md
          - 8.2 最全的前端Git使用教程之手把手带你上手Git实战: 8.2 最全的前端Git使用教程之手把手带你上手Git实战.md
      - 9:
          - 9.1 Web前端学习答疑: 9.1 Web前端学习答疑.md
      - 10:
          - 10.1 CSS基础认知，从零学前端CSS入门第一课: 10.1 CSS基础认知，从零学前端CSS入门第一课.md
          - 10.2 CSS基础选择器详解: 10.2 CSS基础选择器详解.md
      - 11:
          - 11.1 前端入门之CSS字体属性详解: 11.1 前端入门之CSS字体属性详解.md
          - 11.2 前端入门之CSS文本属性详解: 11.2 前端入门之CSS文本属性详解.md
          - 11.3 前端入门之CSS列表样式详解: 11.3 前端入门之CSS列表样式详解.md
      - 12:
          - 12.1 前端入门之CSS盒子模型详细讲解上集: 12.1 前端入门之CSS盒子模型详细讲解上集.md
          - 12.2 前端入门之CSS盒子模型详细讲解下集: 12.2 前端入门之CSS盒子模型详细讲解下集.md
      - 13:
          - 13.1 前端入门之CSS display属性详解: 13.1 前端入门之CSS display属性详解.md
          - 13.2 前端入门教程之CSS background背景属性 上: 13.2 前端入门教程之CSS background背景属性 上.md
      - 14:
          - 14.1前端入门教程之CSS background背景属性 下: 14.1前端入门教程之CSS background背景属性 下.md
          - 14.2 前端入门CSS其他的常用属性详解: 14.2 前端入门CSS其他的常用属性详解.md
      - 15:
          - 15.1 前端入门之CSS复合选择器 上集: 15.1 前端入门之CSS复合选择器 上集.md
          - 15.2 前端入门之CSS复合选择器 下集: 15.2 前端入门之CSS复合选择器 下集.md
      - 16:
          - 16.1 CSS继承性详解: 16.1 CSS继承性详解.md
          - 16.2 CSS层叠性详解: 16.2 CSS层叠性详解.md
          - 16.3 CSS优先级讲解以及问题答疑: 16.3 CSS优先级讲解以及问题答疑.md
      - 17:
          - 17.1 前端CSS Float(浮动)详解: 17.1 前端CSS Float(浮动)详解.md
          - 17.2 前端入门之CSS教程 BFC规范与浏览器差异: 17.2 前端入门之CSS教程 BFC规范与浏览器差异.md
          - 17.3 前端入门之CSS清除浮动: 17.3 前端入门之CSS清除浮动.md
      - 18:
          - 18.1 前端入门之CSS定位之相对定位和绝对定位: 18.1 前端入门之CSS定位之相对定位和绝对定位.md
          - 18.2 前端入门之CSS定位：粘性定位和固定定位篇: 18.2 前端入门之CSS定位：粘性定位和固定定位篇.md
      - 19:
          - 19.1 前端入门教程之CSS层叠上下文: 19.1 前端入门教程之CSS层叠上下文.md
          - 19.2 前端开发应该要了解的，阿里icofont图标库使用方法: 19.2 前端开发应该要了解的，阿里icofont图标库使用方法.md
          - 19.3 前端入门之CSS margin为负值详解: 19.3 前端入门之CSS margin为负值详解.md
      - 20:
          - 20.1 前端入门CSS3圆角阴影与盒子阴影详解: 20.1 前端入门CSS3圆角阴影与盒子阴影详解.md
          - 20.2 前端入门CSS文本阴影、文本省略号、透明度、图片裁切属性讲解: 20.2 前端入门CSS文本阴影、文本省略号、透明度、图片裁切属性讲解.md
      
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
